v0.0.4 (2014-09-29) ------------------- - [#3] - Runs bundler as the daemon user but also does some backflips to try to ensure a little degree of security - [#5] - Using su instead of sudo and writes out console output to daemon.log - [#6] - Full embracing of the hack to try to and rubyify strings and/or normal ruby attributes into the ruby config - Added the exit code in the init script but I don't think it helps alot. I think most failures happen after lita has backgrounded itself.

diff --git a/templates/default/lita.erb b/templates/default/lita.erb
--- a/templates/default/lita.erb
+++ b/templates/default/lita.erb
@@ -29,7 +29,13 @@ pid() {
 
 start() {
   su - $DAEMON_USER bash -c "export HOME=$HOME_DIR; cd $HOME_DIR; $CMD_FILE $CMD_OPTS >><%= node["lita"]["log_dir"] %>/daemon.log 2>&1"
-  echo "* lita is started"
+  rc=$?
+  if [ $rc -gt 0 ]; then
+    echo "* lita failed to start"
+  else
+    echo "* lita is started"
+  fi
+  return $?
 }
 
 stop() {
